name: test build

on:
  pull_request:

env:
  GODOT_VERSION: '4.7'

jobs:
  export:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Monologue export
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install wine
        id: wine_install
        run: |
          sudo apt-get update
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Export game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./builds/
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
          verbose: true
          export_debug: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: ${{ steps.export.outputs.build_directory }}
