name: test

on:
  push:

env:
  GODOT_VERSION: '4.7'

jobs:
  unit-test:
    name: "gdUnit4 Automated Test"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 15
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v6
      - uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          paths: |
            res://unit
